using Microsoft.EntityFrameworkCore;
using MiniBooking.Models;

namespace MiniBooking.Data;

public static class Seeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await db.Database.EnsureCreatedAsync();
        await MigrateAsync(db);   // bảng thêm sau (CareReminders) — EnsureCreated không tạo trên Postgres đã tồn tại
        if (!await db.Orgs.AnyAsync(o => o.Id == TenantContext.DefaultOrgId))
        {
            db.Orgs.Add(new Org { Id = TenantContext.DefaultOrgId, Name = "Demo Service Center", ApiKey = "demo-booking" });
            await db.SaveChangesAsync();
        }
        await SeedAppTypesAsync(db);
        await SeedCavityTypesAsync(db);
    }

    // Loại cuộc hẹn mặc định (Mst_Ser_AppType) — dùng cho phân loại lịch hẹn.
    private static readonly (string Code, string Name)[] DefaultAppTypes =
    {
        ("BD", "Bảo dưỡng định kỳ"),
        ("SC", "Sửa chữa chung"),
        ("BH", "Bảo hành"),
        ("DS", "Đồng sơn"),
        ("CT", "Cứu hộ / Tai nạn"),
    };

    private static async Task SeedAppTypesAsync(AppDbContext db)
    {
        var orgId = TenantContext.DefaultOrgId;
        var existing = await db.AppTypes.Where(x => x.OrgId == orgId).Select(x => x.Code).ToListAsync();
        var set = existing.ToHashSet();
        foreach (var (code, name) in DefaultAppTypes)
            if (!set.Contains(code)) db.AppTypes.Add(new AppType { OrgId = orgId, Code = code, Name = name, Active = true });
        await db.SaveChangesAsync();
    }

    // Loại khoang sửa chữa mặc định (Mst_Compartment / Ser_Cavity.CavityType) — dùng cho ràng buộc khoang theo dịch vụ.
    private static readonly (string Code, string Name)[] DefaultCavityTypes =
    {
        (CavityRules.Maintain, "Bảo dưỡng nhanh"),
        (CavityRules.Repair, "Sửa chữa chung (RO)"),
        (CavityRules.Copper, "Khoang đồng"),
        (CavityRules.Paint, "Khoang sơn (BP)"),
        (CavityRules.PaintBooth, "Buồng sơn"),
        (CavityRules.Parking, "Đỗ xe / giao xe"),
        (CavityRules.Other, "Khác (kiểm tra cuối, thử phanh)"),
    };

    private static async Task SeedCavityTypesAsync(AppDbContext db)
    {
        var orgId = TenantContext.DefaultOrgId;
        var existing = await db.CavityTypes.Where(x => x.OrgId == orgId).Select(x => x.Code).ToListAsync();
        var set = existing.ToHashSet();
        foreach (var (code, name) in DefaultCavityTypes)
            if (!set.Contains(code)) db.CavityTypes.Add(new CavityType { OrgId = orgId, Code = code, Name = name, Active = true });
        await db.SaveChangesAsync();
    }

    private static async Task MigrateAsync(AppDbContext db)
    {
        if (!db.Database.IsNpgsql()) return;
        var stmts = new[]
        {
            "CREATE TABLE IF NOT EXISTS public.\"CareReminders\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"CustomerName\" text NOT NULL DEFAULT '', \"Phone\" text NOT NULL DEFAULT '', \"Vin\" text NULL, \"Plate\" text NULL, \"CareType\" text NOT NULL DEFAULT 'Maintenance', \"DueDate\" timestamp NOT NULL, \"Status\" text NOT NULL DEFAULT 'Pending', \"Note\" text NULL, \"BookingCode\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now(), \"ContactedAt\" timestamp NULL)",
            "CREATE TABLE IF NOT EXISTS public.\"Engineers\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Skill\" text NULL, \"DealerCode\" text NOT NULL DEFAULT '', \"Active\" boolean NOT NULL DEFAULT true)",
            "CREATE TABLE IF NOT EXISTS public.\"ServiceBays\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"BayType\" text NOT NULL DEFAULT 'General', \"CapacityPerSlot\" integer NOT NULL DEFAULT 1, \"DealerCode\" text NOT NULL DEFAULT '', \"Active\" boolean NOT NULL DEFAULT true, \"Note\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"BayCode\" text NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"AppTypeCode\" text NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"SlotFrom\" timestamp NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"SlotTo\" timestamp NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"ContactedAt\" timestamp NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"ContactNote\" text NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"ContactResult\" text NULL",
            "CREATE TABLE IF NOT EXISTS public.\"AppTypes\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Active\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "CREATE TABLE IF NOT EXISTS public.\"CavityTypes\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Active\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "CREATE TABLE IF NOT EXISTS public.\"AppServiceItems\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"AppCode\" text NOT NULL DEFAULT '', \"SerCode\" text NOT NULL DEFAULT '', \"SerName\" text NOT NULL DEFAULT '', \"StdManHour\" numeric NOT NULL DEFAULT 0, \"Note\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "CREATE INDEX IF NOT EXISTS \"IX_AppServiceItems_Org_App_Ser\" ON public.\"AppServiceItems\" (\"OrgId\", \"AppCode\", \"SerCode\")",
            "CREATE TABLE IF NOT EXISTS public.\"AppPartItems\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"AppCode\" text NOT NULL DEFAULT '', \"PartCode\" text NOT NULL DEFAULT '', \"PartName\" text NOT NULL DEFAULT '', \"Unit\" text NOT NULL DEFAULT '', \"Quantity\" numeric NOT NULL DEFAULT 0, \"InventoryQuantity\" numeric NOT NULL DEFAULT 0, \"Note\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "CREATE INDEX IF NOT EXISTS \"IX_AppPartItems_Org_App_Part\" ON public.\"AppPartItems\" (\"OrgId\", \"AppCode\", \"PartCode\")",
            "CREATE TABLE IF NOT EXISTS public.\"RepairOrders\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"RoId\" text NOT NULL DEFAULT '', \"RoNo\" text NOT NULL DEFAULT '', \"DealerCode\" text NOT NULL DEFAULT '', \"CusName\" text NOT NULL DEFAULT '', \"CusTel\" text NULL, \"PlateNo\" text NULL, \"FrameNo\" text NULL, \"CusRequest\" text NULL, \"Status\" text NOT NULL DEFAULT 'Open', \"AppCode\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now(), \"LinkedAt\" timestamp NULL)",
            "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_RepairOrders_Org_RoId\" ON public.\"RepairOrders\" (\"OrgId\", \"RoId\")",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"RoId\" text NULL",
            "CREATE TABLE IF NOT EXISTS public.\"PostServiceCares\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"CusCareId\" text NOT NULL DEFAULT '', \"RoId\" text NULL, \"RoNo\" text NULL, \"CustomerName\" text NOT NULL DEFAULT '', \"Phone\" text NULL, \"Plate\" text NULL, \"FrameNo\" text NULL, \"DealerCode\" text NOT NULL DEFAULT '', \"FinishedDate\" timestamp NULL, \"Status\" text NOT NULL DEFAULT 'PEND', \"ContactDate\" timestamp NULL, \"FyourCSSH\" text NULL, \"WFBasicNeeds\" text NULL, \"YourCarProblem\" text NULL, \"YourRIWN\" text NULL, \"YourSatisfyQSv\" text NULL, \"YourHopeOfOur\" text NULL, \"Note\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_PostServiceCares_Org_CusCareId\" ON public.\"PostServiceCares\" (\"OrgId\", \"CusCareId\")",
            "CREATE TABLE IF NOT EXISTS public.\"ReceptionForms\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"ReceptionFNo\" text NOT NULL DEFAULT '', \"DealerCode\" text NOT NULL DEFAULT '', \"CusName\" text NOT NULL DEFAULT '', \"Phone\" text NULL, \"Plate\" text NULL, \"FrameNo\" text NULL, \"ReceptionType\" text NOT NULL DEFAULT 'Service', \"Status\" text NOT NULL DEFAULT 'P', \"CreatedBy\" text NULL, \"CreatedDateTime\" timestamp NOT NULL DEFAULT now(), \"DeliveryDateTime\" timestamp NULL, \"AppCode\" text NULL, \"RoNo\" text NULL, \"Note\" text NULL)",
            "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ReceptionForms_Org_ReceptionFNo\" ON public.\"ReceptionForms\" (\"OrgId\", \"ReceptionFNo\")",
        };
        foreach (var sql in stmts) try { await db.Database.ExecuteSqlRawAsync(sql); } catch { }
    }
}
