using Microsoft.EntityFrameworkCore;
using MiniBooking.Models;

namespace MiniBooking.Data;

public static class Seeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await db.Database.EnsureCreatedAsync();
        await MigrateAsync(db);   // bảng thêm sau (CareReminders) — EnsureCreated không tạo trên Postgres đã tồn tại
        if (!await db.Orgs.AnyAsync(o => o.Id == TenantContext.DefaultOrgId))
        {
            db.Orgs.Add(new Org { Id = TenantContext.DefaultOrgId, Name = "Demo Service Center", ApiKey = "demo-booking" });
            await db.SaveChangesAsync();
        }
    }

    private static async Task MigrateAsync(AppDbContext db)
    {
        if (!db.Database.IsNpgsql()) return;
        var stmts = new[]
        {
            "CREATE TABLE IF NOT EXISTS public.\"CareReminders\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"CustomerName\" text NOT NULL DEFAULT '', \"Phone\" text NOT NULL DEFAULT '', \"Vin\" text NULL, \"Plate\" text NULL, \"CareType\" text NOT NULL DEFAULT 'Maintenance', \"DueDate\" timestamp NOT NULL, \"Status\" text NOT NULL DEFAULT 'Pending', \"Note\" text NULL, \"BookingCode\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now(), \"ContactedAt\" timestamp NULL)",
            "CREATE TABLE IF NOT EXISTS public.\"Engineers\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Skill\" text NULL, \"DealerCode\" text NOT NULL DEFAULT '', \"Active\" boolean NOT NULL DEFAULT true)",
            "CREATE TABLE IF NOT EXISTS public.\"ServiceBays\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"BayType\" text NOT NULL DEFAULT 'General', \"CapacityPerSlot\" integer NOT NULL DEFAULT 1, \"DealerCode\" text NOT NULL DEFAULT '', \"Active\" boolean NOT NULL DEFAULT true, \"Note\" text NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"BayCode\" text NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"AppTypeCode\" text NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"SlotFrom\" timestamp NULL",
            "ALTER TABLE public.\"Appointments\" ADD COLUMN IF NOT EXISTS \"SlotTo\" timestamp NULL",
        };
        foreach (var sql in stmts) try { await db.Database.ExecuteSqlRawAsync(sql); } catch { }
    }
}
